sudo: required
services:
  - docker

docker_login:
  - docker login kanikachander/docker-react

before_install:
  - docker run -t kanikachander/docker-react -f Dockerfile.dev .

script:
  - docker run kanikachander/docker-react npm run test -- --coverage