sudo: required
services:
  - docker

before_install:
  - docker login kanikachander/docker-react --username=kanikachander --password=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
  - docker build -t kanikachander/docker-react -f Dockerfile.dev .

script:
  - docker run kanikachander/docker-react npm run test -- --coverage