version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:app
  test:
    build:
      dockerfile: Dockerfile.dev
      context: .
    command: ["npm","run","test"]
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:app